### PR TITLE
Release 2.0.1

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Release 2.0.1
| Type?         | bug fix
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | N/A
| How to test?  | Release Test

### CODE REVIEW

**Review by matthieu-rolland — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
hey @Progi1984 

could you rebase this PR so that we could have the PR fixing order confirmation page in v2.0.1?

**Comment by Progi1984** [comment]
@kpodemski It's based on dev branch of the repository. I can't rebase it.

**Comment by Progi1984** [comment]
@kpodemski It now appears.

**Review by florine2623 — APPROVED** [review]
Hello @Progi1984 ,

Sorry for the delay.

Tested on 1.7.8.x, 8.0.x and develop.

https://github.com/PrestaShop/ps_cashondelivery/pull/45
Upgrade went well on all versions of PS.
Screenshot 2022-07-15 at 16 36 25
Screenshot 2022-07-15 at 16 36 54

https://github.com/PrestaShop/ps_cashondelivery/pull/46

FO - all is translated.
Screenshot 2022-07-15 at 16 52 04
Screenshot 2022-07-15 at 16 52 24

Same goes for BO:
Screenshot 2022-07-15 at 16 52 48

And mails:
Screenshot 2022-07-15 at 16 56 55

For me it is QA ✅

**Pull request merged**
